name: mydjangoenv  # Or your desired environment name
channels:
  - conda-forge    # Add channels if you need packages from them (like pygrib)
  - defaults
dependencies:
  - python=3.12    # Specify your Python version
  - django         # Example of a conda-installable package
  - pygrib         # If you want pygrib via conda

  - pip
  - pip:
      - -r requirements.txt # This tells conda to use pip for packages in requirements.txt